### ISSUE TITLE
re: todo

### ISSUE THREAD

**Issue by LichKing112** [LichKing112/portfolio#1]
very sure
- [x] avatar/profile picture not loading
- [x] seo - meta tags and favicon
- [x] /socials - friendslist & social medias
- [x] /projects - known open-source projects and commissions
- [x] startpage - just like those linux users :kekw:

not sure
- [ ] custom themes?
- [ ] multiple languages
- [ ] better design?
- [ ] blog/rss?

**Comment by LichKing112** [comment]
closing this until further changes and update
